### ISSUE TITLE
1.18.2 forge also doesn't work.

### ISSUE THREAD

**Issue by idisaj93** [TeamFelnull/IamMusicPlayer#21]
[06:01:50] [lava-daemon-pool-playback-7-thread-1/ERROR] [de.fe.im.li.co.se.di.la.tr.pl.LocalAudioTrackExecutor/]: Error in playback of https://rr1---sn-ab02a0nfpgxapox-bh2zr.googlevideo.com/videoplayback?expire=1647086509&ei=TTcsYpXeKrLbs8IP-qyh-AE&ip=125.186.8.226&id=o-ADmAUPlqYie1PIleiHp1ursLEFyLoHDrknYLR0ZvEzRn&itag=140&source=youtube&requiressl=yes&mh=4h&mm=31%2C26&mn=sn-ab02a0nfpgxapox-bh2zr%2Csn-30a7ynee&ms=au%2Conr&mv=m&mvi=1&pl=16&initcwndbps=3006250&vprv=1&mime=audio%2Fmp4&gir=yes&clen=2492963&dur=153.994&lmt=1574951700074892&mt=1647064614&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgZAX-wNXjbLRDTYbeP9KfBIKgZdd0BsICpSx_pFJfPFoCIQD0qWLn2xSmT_hlGFIBTA9btj4MPtTnxGMFt95sCpU7vA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgZ9HYeqFjTFeo3ANOapTMMaw-EfY528gPNFKsI27A5cICIQCGd3gXS-XM0Ds3PKjVBEj_hd3r6oXp8O2Ou4mSbH6F-g%3D%3D
dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:293) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAudioTrack.process(MpegAudioTrack.java:51) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.source.http.HttpAudioTrack.process(HttpAudioTrack.java:53) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?] {}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
	Suppressed: dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.78
  os.arch: aarch64
  os.name: Mac OS X
  os.version: 12.3
  java.vendor: Azul Systems, Inc.
  java.version: 17.0.2
  java.runtime.version: 17.0.2+8-LTS
  java.vm.version: 17.0.2+8-LTS
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/w5/nl1zrb5d2tb_4_y6z8wzsnp40000gn/T/lava-jni-natives/1647064713704/libconnector.dylib
	at dev.felnull.imp.libs.com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:88) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:69) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at com.sedmelluq.discord.lavaplayer.natives.aac.AacDecoderLibrary.getInstance(AacDecoderLibrary.java:13) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at com.sedmelluq.discord.lavaplayer.natives.aac.AacDecoder.<init>(AacDecoder.java:32) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.container.common.AacPacketRouter.processInput(AacPacketRouter.java:30) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAacTrackConsumer.consume(MpegAacTrackConsumer.java:78) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.container.mpeg.reader.fragmented.MpegFragmentedFileTrackProvider.provideFrames(MpegFragmentedFileTrackProvider.java:68) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	... 9 more
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/w5/nl1zrb5d2tb_4_y6z8wzsnp40000gn/T/lava-jni-natives/1647064713704/libconnector.dylib
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393) ~[?:?] {}
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?] {}
	at java.lang.System.load(System.java:1953) ~[?:?] {}
	at dev.felnull.imp.libs.com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadFromFile(NativeLibraryLoader.java:118) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadInternal(NativeLibraryLoader.java:110) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:84) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:69) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at com.sedmelluq.discord.lavaplayer.natives.aac.AacDecoderLibrary.getInstance(AacDecoderLibrary.java:13) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at com.sedmelluq.discord.lavaplayer.natives.aac.AacDecoder.<init>(AacDecoder.java:32) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.container.common.AacPacketRouter.processInput(AacPacketRouter.java:30) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAacTrackConsumer.consume(MpegAacTrackConsumer.java:78) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.container.mpeg.reader.fragmented.MpegFragmentedFileTrackProvider.provideFrames(MpegFragmentedFileTrackProvider.java:68) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	at dev.felnull.imp.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275) ~[iammusicplayer-forge-1.18.2-3.6.jar%2355!/:?] {re:classloading}
	... 9 more
[06:01:52] [Finalizer/WARN] [de.fe.im.li.co.se.la.co.na.NativeResourceHolder/]: Should have been closed before finalization (com.sedmelluq.discord.lavaplayer.natives.aac.AacDecoder).

**Comment by MG8853** [comment]
What is your computer using?
M1 or intel？

What is the Minecraft launcher using?
GDLauncher? MinecraftLauncher? other?

Why are you using Java from "Azul Systems, Inc."?
https://adoptium.net/releases.html
https://www.oracle.com/java/technologies/downloads/#jdk17-mac

**Comment by MG8853** [comment]
We attribute it to "aarch64" in "lavaplayer".
It seems that you have to wait until the update of lavaplayer comes.

**Comment by idisaj93** [comment]
Oh.. I use M1 Mac and ManyMC(Fork of MultiMC for M1 Mac / https://github.com/MinecraftMachina/ManyMC)

**Comment by MORIMORI0317** [comment]
I found a lavaplayer native library compiled for M1, so I released a version that included that native library.
https://www.curseforge.com/minecraft/mc-mods/iammusicplayer/files/3687101
I don't have a mac PC with an M1 processor, so please check the operation.

**Comment by idisaj93** [comment]
Wow now it works perfectly on both sides on M1. Thank you for solving the problem!

**Comment by rezzler** [comment]
im having the exact same issue but on fabric 1.18.1 with the mod version 3.4, would it be possible for you to upload an updated version for that too? :)

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/iammusicplayer/files/3765680
We released a version of 1.18.1 that fixed the M1 MAC issue.
I haven't checked the operation because I don't have an M1 MAC, but I think it will work.

**Comment by rezzler** [comment]
I just tried it, but i still get the error 

[Music Loader Thread: 4KGsgpFiswQ/ERROR]: Failed to load music: 4KGsgpFiswQ
java.lang.IllegalStateException: Load failed
	at dev.felnull.imp.client.music.MusicLoadThread.run(MusicLoadThread.java:71) [iammusicplayer-fabric-1.18.1-3.4.1.jar:?]

**Comment by MORIMORI0317** [comment]
I made a mistake in the download URL of the native library.
I fixed the URL, You don't need to update the IMP because the wrong URL will be referenced over the network. Try launching IMP again.
